export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  safelist: [
    'bg-aivar-purple', 'bg-aivar-purple-50', 'bg-aivar-purple-100', 'bg-aivar-purple-200',
    'bg-aivar-purple-500', 'bg-aivar-purple-600', 'bg-aivar-purple-700',
    'hover:bg-aivar-purple-600', 'hover:bg-aivar-purple-700',
    'text-aivar-purple', 'text-aivar-purple-500', 'text-aivar-purple-600', 'text-aivar-purple-700',
    'border-aivar-purple', 'border-aivar-purple-200', 'border-aivar-purple-100',
    'hover:text-aivar-purple', 'hover:border-aivar-purple',
    'hover:bg-aivar-purple-50', 'ring-aivar-accent',
    'bg-aivar-accent', 'text-aivar-accent', 'bg-aivar-dark',
  ],
  theme: {
    extend: {
      colors: {
        'aivar-purple':      '#6C5CE7',
        'aivar-purple-700':  '#5A4BD1',
        'aivar-purple-600':  '#6256DC',
        'aivar-purple-500':  '#7B6FEF',
        'aivar-purple-200':  'var(--color-purple-200)',
        'aivar-purple-100':  'var(--color-purple-100)',
        'aivar-purple-50':   'var(--color-purple-50)',
        'aivar-accent':      '#A29BFE',
        'aivar-accent-600':  '#8B82FE',
        'aivar-accent-100':  'var(--color-purple-50)',
        'aivar-dark':        '#0D1117',
        'aivar-dark-700':    '#161B22',
        'pando-green':       '#6C5CE7',
        'pando-green-700':   '#5A4BD1',
        'pando-green-600':   '#6256DC',
        'pando-green-500':   '#7B6FEF',
        'pando-green-200':   'var(--color-purple-200)',
        'pando-green-100':   'var(--color-purple-100)',
        'pando-green-50':    'var(--color-purple-50)',
        'pando-gold':        '#A29BFE',
        'pando-gold-600':    '#8B82FE',
        'pando-gold-100':    'var(--color-purple-50)',
        background:   'var(--color-bg)',
        surface:      'var(--color-surface)',
        card:         'var(--color-surface)',
        border:       'var(--color-border)',
        'border-dark':'var(--color-border-strong)',
        'text-primary':   'var(--color-text)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted':     'var(--color-text-muted)',
        success: 'rgb(var(--c-success) / <alpha-value>)',
        warning: 'rgb(var(--c-warning) / <alpha-value>)',
        danger:  'rgb(var(--c-danger) / <alpha-value>)',
        'success-bg': 'var(--color-success-bg)',
        'warning-bg': 'var(--color-warning-bg)',
        'danger-bg':  'var(--color-danger-bg)',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Outfit', 'Inter', 'sans-serif'],
        wordmark: ['Syne', 'Outfit', 'sans-serif'],
      },
      boxShadow: {
        card: 'var(--c-shadow)',
        'card-hover': '0 8px 24px rgba(108, 92, 231, 0.12), 0 0 0 1px rgba(108, 92, 231, 0.12)',
        modal: '0 20px 60px rgba(0,0,0,0.35)',
        topbar: '0 1px 0 rgb(var(--c-border))',
      },
    },
  },
  plugins: [],
}
